version: '3'
services:
  app:
    image: flask
    volumes:
      - app:/app
    ports:      
      - "8000:8000"
  proxy:
    image: nginx_local
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  app: